version: '3.9'

services:
  dev_env:
    image: bgmc_devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ..:/workspaces/blockchain-gaming-marketplace-contract:cached
    command: sleep infinity
    networks:
      - dev_network
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - 8545:8545
    networks:
      - dev_network
networks:
  dev_network:
    name: bgmc_dev_network
